<?php
// Start session
session_start();

// Include database configuration and functions
require_once '../includes/config.php';
require_once '../includes/functions.php';

// Check if user is logged in
if (!isLoggedIn()) {
    redirect('index.php');
}

// Get settings
$settings = getSettings($conn);

// Get current theme settings
$themeSettings = [
    'primary_color' => $settings['primary_color'] ?? '#1f77c0',
    'secondary_color' => $settings['secondary_color'] ?? '#ff9900',
    'accent_color' => $settings['accent_color'] ?? '#e44d26',
    'font_family' => $settings['font_family'] ?? 'Roboto, sans-serif',
    'heading_font' => $settings['heading_font'] ?? 'Montserrat, sans-serif',
    'background_color' => $settings['background_color'] ?? '#ffffff',
    'text_color' => $settings['text_color'] ?? '#333333',
    'header_style' => $settings['header_style'] ?? 'standard',
    'footer_style' => $settings['footer_style'] ?? 'standard'
];

// Message to display (if any)
$message = $message ?? '';

// Get available fonts
$googleFonts = [
    'Arial, sans-serif' => 'Arial (System)',
    'Helvetica, sans-serif' => 'Helvetica (System)',
    'Verdana, sans-serif' => 'Verdana (System)',
    'Roboto, sans-serif' => 'Roboto',
    'Open Sans, sans-serif' => 'Open Sans',
    'Lato, sans-serif' => 'Lato',
    'Montserrat, sans-serif' => 'Montserrat',
    'Raleway, sans-serif' => 'Raleway',
    'Oswald, sans-serif' => 'Oswald',
    'Ubuntu, sans-serif' => 'Ubuntu',
    'Poppins, sans-serif' => 'Poppins',
    'Merriweather, serif' => 'Merriweather',
    'Playfair Display, serif' => 'Playfair Display',
];

// Get header/footer styles
$headerStyles = [
    'standard' => 'Standard',
    'transparent' => 'Transparent',
    'centered' => 'Centered Logo',
    'minimal' => 'Minimal'
];

$footerStyles = [
    'standard' => 'Standard (3 columns)',
    'simple' => 'Simple (1 column)',
    'detailed' => 'Detailed (4 columns)',
    'minimal' => 'Minimal'
];

// Handle theme settings update
if ($_SERVER["REQUEST_METHOD"] == "POST" && isset($_POST['update_theme'])) {
    // Prepare settings to be updated
    $updateFields = [];
    
    // Color settings
    $updateFields[] = "primary_color = '" . $conn->real_escape_string($_POST['primary_color']) . "'";
    $updateFields[] = "secondary_color = '" . $conn->real_escape_string($_POST['secondary_color']) . "'";
    $updateFields[] = "accent_color = '" . $conn->real_escape_string($_POST['accent_color']) . "'";
    $updateFields[] = "background_color = '" . $conn->real_escape_string($_POST['background_color']) . "'";
    $updateFields[] = "text_color = '" . $conn->real_escape_string($_POST['text_color']) . "'";
    
    // Font settings
    $updateFields[] = "font_family = '" . $conn->real_escape_string($_POST['font_family']) . "'";
    $updateFields[] = "heading_font = '" . $conn->real_escape_string($_POST['heading_font']) . "'";
    
    // Layout settings
    $updateFields[] = "header_style = '" . $conn->real_escape_string($_POST['header_style']) . "'";
    $updateFields[] = "footer_style = '" . $conn->real_escape_string($_POST['footer_style']) . "'";
    
    // Generate the SQL update statement
    $sql = "UPDATE settings SET " . implode(", ", $updateFields) . " WHERE id = 1";
    
    if ($conn->query($sql) === TRUE) {
        $message = displaySuccess("Theme settings updated successfully!");
        
        // Update local settings array
        $themeSettings = [
            'primary_color' => $_POST['primary_color'],
            'secondary_color' => $_POST['secondary_color'],
            'accent_color' => $_POST['accent_color'],
            'font_family' => $_POST['font_family'],
            'heading_font' => $_POST['heading_font'],
            'background_color' => $_POST['background_color'],
            'text_color' => $_POST['text_color'],
            'header_style' => $_POST['header_style'],
            'footer_style' => $_POST['footer_style']
        ];
        
        // Regenerate CSS file with new settings
        $css = generateCustomCSS($themeSettings);
        file_put_contents("../css/custom-theme.css", $css);
    } else {
        $message = displayError("Error updating theme settings: " . $conn->error);
    }
}

// Generate CSS based on theme settings
function generateCustomCSS($settings) {
    $css = <<<CSS
/* 
 * Custom Theme CSS - Auto-generated by Theme Settings
 * Future Hope Foundation
 */

:root {
    --primary-color: {$settings['primary_color']};
    --secondary-color: {$settings['secondary_color']};
    --accent-color: {$settings['accent_color']};
    --background-color: {$settings['background_color']};
    --text-color: {$settings['text_color']};
}

body {
    font-family: {$settings['font_family']};
    color: {$settings['text_color']};
    background-color: {$settings['background_color']};
}

h1, h2, h3, h4, h5, h6 {
    font-family: {$settings['heading_font']};
}

.btn-primary, 
.bg-primary,
.badge-primary {
    background-color: {$settings['primary_color']} !important;
    border-color: {$settings['primary_color']} !important;
}

.btn-secondary, 
.bg-secondary,
.badge-secondary {
    background-color: {$settings['secondary_color']} !important;
    border-color: {$settings['secondary_color']} !important;
}

.accent-color,
.text-accent {
    color: {$settings['accent_color']} !important;
}

.accent-bg {
    background-color: {$settings['accent_color']} !important;
}

.text-primary {
    color: {$settings['primary_color']} !important;
}

.text-secondary {
    color: {$settings['secondary_color']} !important;
}

a {
    color: {$settings['primary_color']};
}

a:hover {
    color: {$settings['secondary_color']};
}

.navbar.bg-primary {
    background-color: {$settings['primary_color']} !important;
}

/* Header Styles */
CSS;

    // Add header specific CSS based on header style
    switch($settings['header_style']) {
        case 'transparent':
            $css .= <<<CSS
            
/* Transparent Header */
@media (min-width: 992px) {
    .header-transparent {
        position: absolute;
        width: 100%;
        z-index: 1030;
        background-color: transparent !important;
        box-shadow: none;
    }
    
    .header-transparent .navbar {
        background-color: transparent !important;
        padding-top: 20px;
        padding-bottom: 20px;
    }
    
    .header-transparent .nav-link {
        color: #fff !important;
    }
}
CSS;
            break;
            
        case 'centered':
            $css .= <<<CSS
            
/* Centered Logo Header */
.header-centered .navbar-brand {
    position: absolute;
    left: 50%;
    transform: translateX(-50%);
}

@media (min-width: 992px) {
    .header-centered .navbar-nav:first-of-type {
        margin-right: auto;
    }
    
    .header-centered .navbar-nav:last-of-type {
        margin-left: auto;
    }
}
CSS;
            break;
            
        case 'minimal':
            $css .= <<<CSS
            
/* Minimal Header */
.header-minimal .navbar {
    padding-top: 5px;
    padding-bottom: 5px;
}

.header-minimal .navbar-brand img {
    max-height: 40px;
}
CSS;
            break;
    }
    
    // Add footer specific CSS
    $css .= "\n\n/* Footer Styles */";
    
    switch($settings['footer_style']) {
        case 'simple':
            $css .= <<<CSS
            
/* Simple Footer */
.footer-simple {
    padding: 30px 0;
    text-align: center;
}
CSS;
            break;
            
        case 'detailed':
            $css .= <<<CSS
            
/* Detailed Footer */
.footer-detailed {
    padding: 60px 0 30px;
    background-color: #222;
    color: #fff;
}

.footer-detailed h5 {
    border-bottom: 2px solid {$settings['accent_color']};
    padding-bottom: 10px;
    margin-bottom: 20px;
}
CSS;
            break;
            
        case 'minimal':
            $css .= <<<CSS
            
/* Minimal Footer */
.footer-minimal {
    padding: 20px 0;
    background-color: #f8f9fa;
    color: #555;
}
CSS;
            break;
    }

    return $css;
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manage Theme Settings - <?php echo $settings['site_name'] ?? 'Future Hope'; ?> Admin</title>
    
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@400;500;600&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@400;500;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;600;700&display=swap" rel="stylesheet">
    
    <!-- Spectrum Color Picker CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/spectrum/1.8.1/spectrum.min.css">
    
    <!-- Custom Admin CSS -->
    <link rel="stylesheet" href="css/admin-style.css">
    
    <style>
        body {
            background-color: #f8f9fa;
            font-family: 'Roboto', sans-serif;
            padding-top: 56px;
        }
        
        .sidebar {
            position: fixed;
            top: 56px;
            left: 0;
            width: 250px;
            height: calc(100vh - 56px);
            background-color: #343a40;
            color: #fff;
            overflow-y: auto;
            transition: all 0.3s;
            z-index: 1000;
        }
        
        .sidebar .nav-link {
            color: rgba(255, 255, 255, 0.75);
            padding: 12px 20px;
            transition: all 0.3s;
        }
        
        .sidebar .nav-link:hover {
            color: #fff;
            background-color: rgba(255, 255, 255, 0.1);
        }
        
        .sidebar .nav-link.active {
            color: #fff;
            background-color: #3498db;
        }
        
        .sidebar .nav-link i {
            margin-right: 10px;
            width: 20px;
            text-align: center;
        }
        
        .content-wrapper {
            margin-left: 250px;
            padding: 20px;
            transition: all 0.3s;
        }
        
        @media (max-width: 991px) {
            .sidebar {
                width: 60px;
            }
            
            .sidebar .nav-link span {
                display: none;
            }
            
            .sidebar .nav-link i {
                margin-right: 0;
                font-size: 18px;
            }
            
            .content-wrapper {
                margin-left: 60px;
            }
        }
        
        .color-preview {
            display: inline-block;
            width: 25px;
            height: 25px;
            border-radius: 50%;
            vertical-align: middle;
            margin-right: 10px;
            border: 1px solid #ddd;
        }
        
        .font-preview {
            font-size: 18px;
            margin-bottom: 5px;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
        }
        
        .theme-preview {
            border: 1px solid #ddd;
            border-radius: 5px;
            padding: 15px;
            margin-bottom: 20px;
        }
        
        .theme-preview-header {
            background-color: #f8f9fa;
            padding: 10px;
            margin-bottom: 15px;
            border-radius: 3px;
        }
        
        .theme-preview-content {
            margin-bottom: 15px;
        }
        
        .theme-preview-footer {
            background-color: #f8f9fa;
            padding: 10px;
            border-radius: 3px;
        }
    </style>
</head>
<body>
    <!-- Top Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="dashboard.php">
                <?php echo $settings['site_name'] ?? 'Future Hope Foundation'; ?> Admin
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="../index.php" target="_blank">
                            <i class="fas fa-external-link-alt"></i> View Website
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-user-circle"></i> <?php echo $_SESSION['username']; ?>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="profile.php"><i class="fas fa-user me-2"></i> Profile</a></li>
                            <li><a class="dropdown-item" href="change-password.php"><i class="fas fa-key me-2"></i> Change Password</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="logout.php"><i class="fas fa-sign-out-alt me-2"></i> Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    
    <!-- Sidebar -->
    <div class="sidebar">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link" href="dashboard.php">
                    <i class="fas fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="settings.php">
                    <i class="fas fa-cog"></i>
                    <span>Site Settings</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="sliders.php">
                    <i class="fas fa-images"></i>
                    <span>Manage Sliders</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="services.php">
                    <i class="fas fa-hands-helping"></i>
                    <span>Services</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="projects.php">
                    <i class="fas fa-project-diagram"></i>
                    <span>Projects</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="events.php">
                    <i class="fas fa-calendar-alt"></i>
                    <span>Events</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="team.php">
                    <i class="fas fa-users"></i>
                    <span>Team Members</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="testimonials.php">
                    <i class="fas fa-quote-left"></i>
                    <span>Testimonials</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="gallery.php">
                    <i class="fas fa-photo-video"></i>
                    <span>Gallery</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="donations.php">
                    <i class="fas fa-donate"></i>
                    <span>Donations</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="messages.php">
                    <i class="fas fa-envelope"></i>
                    <span>Messages</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="users.php">
                    <i class="fas fa-user-shield"></i>
                    <span>Users</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="themes.php">
                    <i class="fas fa-paint-brush"></i>
                    <span>Theme Settings</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="logout.php">
                    <i class="fas fa-sign-out-alt"></i>
                    <span>Logout</span>
                </a>
            </li>
        </ul>
    </div>
    
    <!-- Content Wrapper -->
    <div class="content-wrapper">
        <div class="container-fluid">
            <!-- Page Title -->
            <div class="row">
                <div class="col-12">
                    <div class="d-flex justify-content-between align-items-center mb-4">
                        <div>
                            <h1 class="mb-0">Manage Theme Settings</h1>
                            <p class="text-muted">Customize your website appearance</p>
                        </div>
                    </div>
                </div>
            </div>
            
            <?php echo $message; ?>
            
            <div class="row">
                <div class="col-lg-8">
                    <div class="card">
                        <div class="card-header">
                            <h5 class="mb-0 text-primary"><i class="fas fa-paint-brush me-2"></i> Theme Customization</h5>
                        </div>
                        <div class="card-body">
                            <form action="themes.php" method="post">
                                <div class="row">
                                    <!-- Color Settings -->
                                    <div class="col-md-6">
                                        <h5 class="border-bottom pb-2 mb-3">Color Scheme</h5>
                                        
                                        <div class="mb-3">
                                            <label for="primary_color" class="form-label">Primary Color</label>
                                            <div class="input-group">
                                                <span class="input-group-text">
                                                    <span class="color-preview" style="background-color: <?php echo $themeSettings['primary_color']; ?>"></span>
                                                </span>
                                                <input type="text" class="form-control color-picker" id="primary_color" name="primary_color" value="<?php echo $themeSettings['primary_color']; ?>">
                                            </div>
                                            <small class="text-muted">Used for buttons, headings, and main elements</small>
                                        </div>
                                        
                                        <div class="mb-3">
                                            <label for="secondary_color" class="form-label">Secondary Color</label>
                                            <div class="input-group">
                                                <span class="input-group-text">
                                                    <span class="color-preview" style="background-color: <?php echo $themeSettings['secondary_color']; ?>"></span>
                                                </span>
                                                <input type="text" class="form-control color-picker" id="secondary_color" name="secondary_color" value="<?php echo $themeSettings['secondary_color']; ?>">
                                            </div>
                                            <small class="text-muted">Used for accents and secondary elements</small>
                                        </div>
                                        
                                        <div class="mb-3">
                                            <label for="accent_color" class="form-label">Accent Color</label>
                                            <div class="input-group">
                                                <span class="input-group-text">
                                                    <span class="color-preview" style="background-color: <?php echo $themeSettings['accent_color']; ?>"></span>
                                                </span>
                                                <input type="text" class="form-control color-picker" id="accent_color" name="accent_color" value="<?php echo $themeSettings['accent_color']; ?>">
                                            </div>
                                            <small class="text-muted">Used for highlights and call-to-actions</small>
                                        </div>
                                        
                                        <div class="mb-3">
                                            <label for="background_color" class="form-label">Background Color</label>
                                            <div class="input-group">
                                                <span class="input-group-text">
                                                    <span class="color-preview" style="background-color: <?php echo $themeSettings['background_color']; ?>"></span>
                                                </span>
                                                <input type="text" class="form-control color-picker" id="background_color" name="background_color" value="<?php echo $themeSettings['background_color']; ?>">
                                            </div>
                                            <small class="text-muted">Main background color</small>
                                        </div>
                                        
                                        <div class="mb-3">
                                            <label for="text_color" class="form-label">Text Color</label>
                                            <div class="input-group">
                                                <span class="input-group-text">
                                                    <span class="color-preview" style="background-color: <?php echo $themeSettings['text_color']; ?>"></span>
                                                </span>
                                                <input type="text" class="form-control color-picker" id="text_color" name="text_color" value="<?php echo $themeSettings['text_color']; ?>">
                                            </div>
                                            <small class="text-muted">Default text color</small>
                                        </div>
                                    </div>
                                    
                                    <!-- Typography & Layout Settings -->
                                    <div class="col-md-6">
                                        <h5 class="border-bottom pb-2 mb-3">Typography</h5>
                                        
                                        <div class="mb-3">
                                            <label for="font_family" class="form-label">Body Font</label>
                                            <select class="form-select" id="font_family" name="font_family">
                                                <?php foreach ($googleFonts as $value => $label): ?>
                                                <option value="<?php echo $value; ?>" <?php echo ($themeSettings['font_family'] === $value) ? 'selected' : ''; ?>><?php echo $label; ?></option>
                                                <?php endforeach; ?>
                                            </select>
                                            <div class="mt-2 font-preview" style="font-family: <?php echo $themeSettings['font_family']; ?>;">
                                                The quick brown fox jumps over the lazy dog.
                                            </div>
                                        </div>
                                        
                                        <div class="mb-3">
                                            <label for="heading_font" class="form-label">Heading Font</label>
                                            <select class="form-select" id="heading_font" name="heading_font">
                                                <?php foreach ($googleFonts as $value => $label): ?>
                                                <option value="<?php echo $value; ?>" <?php echo ($themeSettings['heading_font'] === $value) ? 'selected' : ''; ?>><?php echo $label; ?></option>
                                                <?php endforeach; ?>
                                            </select>
                                            <div class="mt-2">
                                                <h3 class="font-preview" style="font-family: <?php echo $themeSettings['heading_font']; ?>;">
                                                    Heading Example
                                                </h3>
                                            </div>
                                        </div>
                                        
                                        <h5 class="border-bottom pb-2 mb-3 mt-4">Layout Options</h5>
                                        
                                        <div class="mb-3">
                                            <label for="header_style" class="form-label">Header Style</label>
                                            <select class="form-select" id="header_style" name="header_style">
                                                <?php foreach ($headerStyles as $value => $label): ?>
                                                <option value="<?php echo $value; ?>" <?php echo ($themeSettings['header_style'] === $value) ? 'selected' : ''; ?>><?php echo $label; ?></option>
                                                <?php endforeach; ?>
                                            </select>
                                        </div>
                                        
                                        <div class="mb-3">
                                            <label for="footer_style" class="form-label">Footer Style</label>
                                            <select class="form-select" id="footer_style" name="footer_style">
                                                <?php foreach ($footerStyles as $value => $label): ?>
                                                <option value="<?php echo $value; ?>" <?php echo ($themeSettings['footer_style'] === $value) ? 'selected' : ''; ?>><?php echo $label; ?></option>
                                                <?php endforeach; ?>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="mt-4 text-end">
                                    <button type="submit" name="update_theme" class="btn btn-primary">
                                        <i class="fas fa-save me-1"></i> Save Theme Settings
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                
                <div class="col-lg-4">
                    <div class="card sticky-top" style="top: 80px; z-index: 100;">
                        <div class="card-header">
                            <h5 class="mb-0 text-primary"><i class="fas fa-eye me-2"></i> Live Preview</h5>
                        </div>
                        <div class="card-body">
                            <div class="theme-preview">
                                <div id="preview-header" class="theme-preview-header">
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="fw-bold">Site Name</div>
                                        <div>
                                            <span class="badge rounded-pill" style="background-color: <?php echo $themeSettings['primary_color']; ?>;">Home</span>
                                            <span class="badge rounded-pill bg-secondary">About</span>
                                        </div>
                                    </div>
                                </div>
                                
                                <div id="preview-content" class="theme-preview-content">
                                    <h4 id="preview-heading" style="color: <?php echo $themeSettings['primary_color']; ?>; font-family: <?php echo $themeSettings['heading_font']; ?>;">Sample Heading</h4>
                                    <p id="preview-paragraph" style="color: <?php echo $themeSettings['text_color']; ?>; font-family: <?php echo $themeSettings['font_family']; ?>;">
                                        This is sample content that shows how your selected colors and fonts will look on your website.
                                    </p>
                                    <button id="preview-button" class="btn btn-sm" style="background-color: <?php echo $themeSettings['primary_color']; ?>; color: white;">Primary Button</button>
                                    <button id="preview-secondary-button" class="btn btn-sm" style="background-color: <?php echo $themeSettings['secondary_color']; ?>; color: white;">Secondary</button>
                                    <a href="#" id="preview-link" style="color: <?php echo $themeSettings['accent_color']; ?>; text-decoration: none;">Sample Link</a>
                                </div>
                                
                                <div id="preview-footer" class="theme-preview-footer">
                                    <small>Footer Preview</small>
                                </div>
                            </div>
                            
                            <div class="alert alert-info">
                                <i class="fas fa-info-circle me-2"></i> This is a simplified preview. Changes will be applied to the live site after saving.
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    
    <!-- Spectrum Color Picker -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/spectrum/1.8.1/spectrum.min.js"></script>
    
    <script>
        $(document).ready(function() {
            // Initialize color pickers
            $(".color-picker").spectrum({
                showInput: true,
                preferredFormat: "hex",
                showPalette: true,
                palette: [
                    ["#1f77c0", "#ff9900", "#e44d26", "#2ecc71", "#9b59b6"],
                    ["#f1c40f", "#e67e22", "#3498db", "#e74c3c", "#1abc9c"],
                    ["#34495e", "#16a085", "#d35400", "#8e44ad", "#2c3e50"]
                ],
                change: function(color) {
                    updatePreview();
                }
            });
            
            // Update preview when font selections change
            $('#font_family, #heading_font').change(function() {
                updatePreview();
            });
            
            // Update layout styles when selections change
            $('#header_style, #footer_style').change(function() {
                // This would be more complex in a real implementation
                // For now, just indicate the change
                $('#preview-header').css('opacity', '0.8').animate({opacity: 1}, 500);
                $('#preview-footer').css('opacity', '0.8').animate({opacity: 1}, 500);
            });
            
            // Function to update the live preview
            function updatePreview() {
                var primaryColor = $('#primary_color').val();
                var secondaryColor = $('#secondary_color').val();
                var accentColor = $('#accent_color').val();
                var backgroundColor = $('#background_color').val();
                var textColor = $('#text_color').val();
                var fontFamily = $('#font_family').val();
                var headingFont = $('#heading_font').val();
                
                // Update preview elements
                $('#preview-heading').css({
                    'color': primaryColor,
                    'font-family': headingFont
                });
                
                $('#preview-paragraph').css({
                    'color': textColor,
                    'font-family': fontFamily
                });
                
                $('#preview-button').css('background-color', primaryColor);
                $('#preview-secondary-button').css('background-color', secondaryColor);
                $('#preview-link').css('color', accentColor);
                
                // Update color preview circles
                $('.color-preview').each(function() {
                    var input = $(this).closest('.input-group').find('.color-picker');
                    $(this).css('background-color', input.val());
                });
                
                // Update font previews
                $('.font-preview').first().css('font-family', fontFamily);
                $('.font-preview').last().css('font-family', headingFont);
            }
        });
    </script>
</body>
</html>
